name: CI/CD

on:
  push:
  pull_request:

env:
  NODE_VERSION: 14.x


jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build
          node-version: ${{env.NODE_VERSION}}
      - uses: noi-techpark/github-actions/webcomp-test@v2

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_ODH_BASE_URL: "https://mobility.api.opendatahub.testingmachine.eu/v2/flat/NOI-Place"
          X_ODH_RESOURCE_URL: "https://images.maps.noi.opendatahub.testingmachine.eu"
          X_ODH_ORIGIN: "webcomp-maps-noi"

      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build
          node-version: ${{env.NODE_VERSION}}

      - uses: noi-techpark/github-actions/webcomp-push@v2
        with:
          keycloak-secret: ${{secrets.WCSTORE_CLI_KEYCLOAK_SECRET_TEST}}
          version-tag: ${{github.sha}}

  deploy-prod:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    concurrency: deploy-prod
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_ODH_BASE_URL: "https://mobility.api.opendatahub.com/v2/flat/NOI-Place"
          X_ODH_RESOURCE_URL: "https://images.maps.noi.opendatahub.bz.it"
          X_ODH_ORIGIN: "webcomp-maps-noi"

      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build
          node-version: ${{env.NODE_VERSION}}

      - uses: noi-techpark/github-actions/webcomp-push@v2
        with:
          keycloak-secret: ${{secrets.WCSTORE_CLI_KEYCLOAK_SECRET_PROD}}
          version-tag: ${{github.ref_name}}
          production: "true"
